### ISSUE TITLE
 missing 1 required positional argument: 'password'

### ISSUE THREAD

**Issue by gebtig01** [mistermax80/ialarm_mk2#2]
Ciao, ho unzipatto il componente nella custom_components e riavviato. In fase di aggiunta dell'integrazione mi esce "Unexpected error" e nei log trovo quanto segue:

```
2024-11-19 22:33:01.671 ERROR (MainThread) [custom_components.ialarm_mk2.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/ialarm_mk2/config_flow.py", line 58, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ialarm_mk2/config_flow.py", line 32, in validate_input
    hub = IAlarmMkHub(data[CONF_HOST], data[CONF_PORT], data[CONF_USERNAME], data[CONF_PASSWORD])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: IAlarmMkHub.__init__() missing 1 required positional argument: 'password'
```

Sto sbagliando qualcosa? La mie versioni di HA sono le seguenti:
Core 2024.11.2
Supervisor 2024.11.2
Operating System 13.2
Frontend 20241106.2

Grazie per il tuo lavoro

**Comment by mistermax80** [comment]
Ok grazie, ti aggiorno.

**Comment by mistermax80** [comment]
hai inserito tutti e 4 i parametri? compresa la password?

**Comment by gebtig01** [comment]
Si, IP, porta, ID centralina (non inizia con CAB ma con numeri e la password

**Comment by mistermax80** [comment]
Ho rilasciato una nuova versione, che risolve il problema, fammi sapere.
#ac9c7d2
